name: mux
on: [push]
jobs:
  build: 
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        # not neccessary because go compat promise, but just in case. 
        go-version: ['1.12', '1.13', '1.14', '1.15', '1.16', '1.17', '1.18', '1.19', '1.20']
  steps: 
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test ./...
      - name: Race
        run: go test --race ./... 

  lints:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.29
